"""initial schema

Revision ID: 8d8e7f8c0b37
Revises:
Create Date: 2026-03-01 20:34:16.851613

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8d8e7f8c0b37"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "spaces",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("currency_code", sa.Text(), nullable=False),
        sa.Column("timezone", sa.Text(), nullable=False),
        sa.Column("default_tax_pct", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("google_id", sa.Text(), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("avatar_url", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("google_id"),
    )
    op.create_table(
        "categories",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("space_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("normalized_name", sa.Text(), nullable=False),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["space_id"],
            ["spaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("space_id", "normalized_name"),
    )
    op.create_table(
        "invite_links",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("space_id", sa.UUID(), nullable=False),
        sa.Column("token", sa.Text(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("expires_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("used_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("used_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["space_id"],
            ["spaces.id"],
        ),
        sa.ForeignKeyConstraint(
            ["used_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
    )
    op.create_table(
        "limits",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("space_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("timeframe", sa.Text(), nullable=False),
        sa.Column(
            "threshold_amount", sa.Numeric(precision=12, scale=2), nullable=False
        ),
        sa.Column("warning_pct", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "timeframe IN ('weekly', 'monthly', 'quarterly', 'yearly')",
            name="ck_limits_timeframe",
        ),
        sa.CheckConstraint(
            "threshold_amount >= 0.01 AND threshold_amount <= 999999.99",
            name="ck_limits_threshold_amount",
        ),
        sa.ForeignKeyConstraint(
            ["space_id"],
            ["spaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "monthly_wraps",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("space_id", sa.UUID(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("month", sa.Integer(), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["space_id"],
            ["spaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("space_id", "year", "month"),
    )
    op.create_table(
        "payment_methods",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("space_id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=True),
        sa.Column("label", sa.String(length=50), nullable=False),
        sa.Column("color", sa.Text(), nullable=True),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["space_id"],
            ["spaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "space_members",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("space_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "joined_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["space_id"],
            ["spaces.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("space_id", "user_id"),
    )
    op.create_table(
        "tags",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("space_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["space_id"],
            ["spaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("space_id", "name"),
    )
    op.create_table(
        "limit_filters",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("limit_id", sa.UUID(), nullable=False),
        sa.Column("filter_type", sa.Text(), nullable=False),
        sa.Column("filter_value", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "filter_type IN ('category', 'merchant', 'tag', 'spender', 'beneficiary', 'payment_method')",
            name="ck_limit_filters_filter_type",
        ),
        sa.ForeignKeyConstraint(["limit_id"], ["limits.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "merchants",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("space_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("normalized_name", sa.Text(), nullable=False),
        sa.Column("last_category_id", sa.UUID(), nullable=True),
        sa.Column("use_count", sa.Integer(), nullable=False),
        sa.Column(
            "last_used_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["last_category_id"], ["categories.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["space_id"],
            ["spaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("space_id", "normalized_name"),
    )
    op.create_table(
        "recurring_templates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("space_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("schedule", sa.Text(), nullable=False),
        sa.Column("default_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("default_merchant", sa.Text(), nullable=False),
        sa.Column("default_category_id", sa.UUID(), nullable=False),
        sa.Column("default_spender_id", sa.UUID(), nullable=False),
        sa.Column("default_beneficiary_type", sa.Text(), nullable=True),
        sa.Column("default_beneficiary_id", sa.UUID(), nullable=True),
        sa.Column("default_payment_method_id", sa.UUID(), nullable=True),
        sa.Column(
            "default_tags",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("next_due_date", sa.Date(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "default_beneficiary_type IN ('member', 'shared')",
            name="ck_recurring_templates_default_beneficiary_type",
        ),
        sa.CheckConstraint(
            "schedule IN ('weekly', 'monthly', 'quarterly', 'yearly')",
            name="ck_recurring_templates_schedule",
        ),
        sa.CheckConstraint(
            "default_amount >= 0.01 AND default_amount <= 999999.99",
            name="ck_recurring_templates_default_amount",
        ),
        sa.ForeignKeyConstraint(
            ["default_beneficiary_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["default_category_id"],
            ["categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["default_payment_method_id"], ["payment_methods.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["default_spender_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["space_id"],
            ["spaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "expenses",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("space_id", sa.UUID(), nullable=False),
        sa.Column("merchant", sa.Text(), nullable=False),
        sa.Column("merchant_normalized", sa.Text(), nullable=False),
        sa.Column(
            "purchase_datetime", postgresql.TIMESTAMP(timezone=True), nullable=False
        ),
        sa.Column("total_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("spender_id", sa.UUID(), nullable=False),
        sa.Column("payment_method_id", sa.UUID(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("recurring_template_id", sa.UUID(), nullable=True),
        sa.Column("scheduled_date", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('confirmed', 'pending')", name="ck_expenses_status"
        ),
        sa.CheckConstraint(
            "total_amount >= 0.01 AND total_amount <= 999999.99",
            name="ck_expenses_total_amount",
        ),
        sa.ForeignKeyConstraint(
            ["payment_method_id"], ["payment_methods.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["recurring_template_id"], ["recurring_templates.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["space_id"],
            ["spaces.id"],
        ),
        sa.ForeignKeyConstraint(
            ["spender_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "expense_lines",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("expense_id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=False),
        sa.Column("beneficiary_type", sa.Text(), nullable=True),
        sa.Column("beneficiary_id", sa.UUID(), nullable=True),
        sa.Column("line_order", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "beneficiary_type IN ('member', 'shared')",
            name="ck_expense_lines_beneficiary_type",
        ),
        sa.CheckConstraint(
            "amount >= 0.01 AND amount <= 999999.99", name="ck_expense_lines_amount"
        ),
        sa.ForeignKeyConstraint(
            ["beneficiary_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["category_id"], ["categories.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["expense_id"], ["expenses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "expense_line_tags",
        sa.Column("expense_line_id", sa.UUID(), nullable=False),
        sa.Column("tag_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["expense_line_id"], ["expense_lines.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.id"],
        ),
        sa.PrimaryKeyConstraint("expense_line_id", "tag_id"),
    )
    # ### end Alembic commands ###

    # --- Custom indexes from ARCHITECTURE.md §5.2 ---

    # Expense queries
    op.execute(
        "CREATE INDEX idx_expenses_space_purchase"
        " ON expenses(space_id, purchase_datetime DESC)"
    )
    op.create_index("idx_expenses_space_status", "expenses", ["space_id", "status"])
    op.create_index(
        "idx_expenses_space_merchant",
        "expenses",
        ["space_id", "merchant_normalized"],
    )
    op.execute(
        "CREATE INDEX idx_expenses_space_spender"
        " ON expenses(space_id, spender_id, purchase_datetime DESC)"
    )
    op.create_index(
        "idx_expenses_space_payment",
        "expenses",
        ["space_id", "payment_method_id"],
    )

    # Expense line queries
    op.create_index("idx_expense_lines_expense", "expense_lines", ["expense_id"])
    op.create_index("idx_expense_lines_category", "expense_lines", ["category_id"])

    # Merchant autocomplete
    op.create_index(
        "idx_merchants_space_name",
        "merchants",
        ["space_id", "normalized_name"],
    )
    op.execute(
        "CREATE INDEX idx_merchants_space_usage"
        " ON merchants(space_id, use_count DESC)"
    )

    # Tag autocomplete
    op.create_index("idx_tags_space_name", "tags", ["space_id", "name"])

    # Limits
    op.create_index("idx_limits_space", "limits", ["space_id"])
    op.create_index("idx_limit_filters_limit", "limit_filters", ["limit_id"])

    # Recurring (V0.5+)
    op.create_index(
        "idx_recurring_space_active",
        "recurring_templates",
        ["space_id", "is_active", "next_due_date"],
    )

    # Invite links
    op.create_index("idx_invite_links_token", "invite_links", ["token"])


def downgrade() -> None:
    """Downgrade schema."""
    # --- Drop custom indexes ---
    op.drop_index("idx_invite_links_token", table_name="invite_links")
    op.drop_index("idx_recurring_space_active", table_name="recurring_templates")
    op.drop_index("idx_limit_filters_limit", table_name="limit_filters")
    op.drop_index("idx_limits_space", table_name="limits")
    op.drop_index("idx_tags_space_name", table_name="tags")
    op.drop_index("idx_merchants_space_usage", table_name="merchants")
    op.drop_index("idx_merchants_space_name", table_name="merchants")
    op.drop_index("idx_expense_lines_category", table_name="expense_lines")
    op.drop_index("idx_expense_lines_expense", table_name="expense_lines")
    op.drop_index("idx_expenses_space_payment", table_name="expenses")
    op.drop_index("idx_expenses_space_spender", table_name="expenses")
    op.drop_index("idx_expenses_space_merchant", table_name="expenses")
    op.drop_index("idx_expenses_space_status", table_name="expenses")
    op.drop_index("idx_expenses_space_purchase", table_name="expenses")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("expense_line_tags")
    op.drop_table("expense_lines")
    op.drop_table("expenses")
    op.drop_table("recurring_templates")
    op.drop_table("merchants")
    op.drop_table("limit_filters")
    op.drop_table("tags")
    op.drop_table("space_members")
    op.drop_table("payment_methods")
    op.drop_table("monthly_wraps")
    op.drop_table("limits")
    op.drop_table("invite_links")
    op.drop_table("categories")
    op.drop_table("users")
    op.drop_table("spaces")
    # ### end Alembic commands ###
